repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.261  # Use the latest stable version
    hooks:
      - id: ruff
        args: [--fix, "--line-length=160"]



  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
